# -*- coding: utf-8 -*-
"""CS_871_ML_Assgn_5_MSS_(538822)_Sloan Digital Sky Survey (SDSS) .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GnuqV3eJaT1JZR6EftNzUIk44PeHBYuU
"""

import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv('Skyserver_SQL12_20_2025 1_03_09 PM.csv', skiprows=1)

# Display basic information
print("="*60)
print("✓ DATASET LOADED SUCCESSFULLY!")
print("="*60)
print(f"\n📊 Total Galaxies: {df.shape[0]}")
print(f"📋 Total Features: {df.shape[1]}")
print(f"\n✅ Column Names:")
print(df.columns.tolist())
print(f"\n🔍 First 5 Galaxies:")
print(df.head())

# Check data quality
print("="*60)
print("📊 DATA QUALITY CHECK")
print("="*60)

# 1. Missing values
print("\n❓ Missing Values:")
print(df.isnull().sum())

# 2. Data types
print("\n📈 Data Types:")
print(df.dtypes)

# 3. Basic statistics
print("\n📉 Basic Statistics:")
print(df.describe())

# 4. Check for unusual values in Petrosian radii
print("\n⚠️  Checking for -9999 (missing data indicators):")
print(f"petroRad_r:  {(df['petroRad_r'] == -9999).sum()} rows")
print(f"petroR50_r:  {(df['petroR50_r'] == -9999).sum()} rows")
print(f"petroR90_r:  {(df['petroR90_r'] == -9999).sum()} rows")

# Replace -9999 with NaN
df['petroR50_r'] = df['petroR50_r'].replace(-9999, np.nan)
df['petroR90_r'] = df['petroR90_r'].replace(-9999, np.nan)

# Fill NaN with median values
df['petroR50_r'].fillna(df['petroR50_r'].median(), inplace=True)
df['petroR90_r'].fillna(df['petroR90_r'].median(), inplace=True)

# Verify cleaning
print("="*60)
print("✓ DATA CLEANING COMPLETED!")
print("="*60)
print("\n✅ Verification:")
print(f"petroR50_r - Missing values: {df['petroR50_r'].isnull().sum()}")
print(f"petroR50_r - Min value: {df['petroR50_r'].min():.3f}")
print(f"\npetroR90_r - Missing values: {df['petroR90_r'].isnull().sum()}")
print(f"petroR90_r - Min value: {df['petroR90_r'].min():.3f}")
print(f"\n📊 Total clean galaxies: {df.shape[0]}")

# Create galaxy color features (magnitude differences)
df['u-g'] = df['u'] - df['g']
df['g-r'] = df['g'] - df['r']
df['r-i'] = df['r'] - df['i']
df['i-z'] = df['i'] - df['z']

# Verify new features
print("="*60)
print("✓ GALAXY COLOR FEATURES CREATED!")
print("="*60)
print(f"\n📊 Total Features Now: {df.shape[1]}")
print(f"\n✅ New Color Columns:")
print(['u-g', 'g-r', 'r-i', 'i-z'])
print(f"\n🔍 First 5 Galaxies with Colors:")
print(df[['objID', 'u', 'g', 'r', 'i', 'z', 'u-g', 'g-r', 'r-i', 'i-z', 'redshift']].head())
print(f"\n📈 Color Statistics:")
print(df[['u-g', 'g-r', 'r-i', 'i-z']].describe())

# Select features for clustering (exclude objID, ra, dec, class)
feature_columns = ['u', 'g', 'r', 'i', 'z',
                   'redshift',
                   'petroRad_r', 'petroR50_r', 'petroR90_r',
                   'u-g', 'g-r', 'r-i', 'i-z']

# Create feature matrix
X = df[feature_columns].copy()

print("="*60)
print("✓ FEATURES SELECTED FOR CLUSTERING!")
print("="*60)
print(f"\n📊 Feature Matrix Shape: {X.shape}")
print(f"   (Rows = Galaxies, Columns = Features)")
print(f"\n✅ Selected Features ({len(feature_columns)}):")
for i, col in enumerate(feature_columns, 1):
    print(f"   {i}. {col}")
print(f"\n🔍 First 5 Rows:")
print(X.head())
print(f"\n📈 Feature Statistics:")
print(X.describe())

from sklearn.preprocessing import StandardScaler

# Initialize the scaler
scaler = StandardScaler()

# Fit and transform the features
X_scaled = scaler.fit_transform(X)

# Convert back to DataFrame for easier viewing
X_scaled_df = pd.DataFrame(X_scaled, columns=feature_columns)

print("="*60)
print("✓ FEATURES SCALED SUCCESSFULLY!")
print("="*60)
print(f"\n📊 Scaled Data Shape: {X_scaled.shape}")
print(f"\n✅ Verification (all features should have mean≈0, std≈1):")
print(X_scaled_df.describe())
print(f"\n🔍 First 5 Scaled Galaxies:")
print(X_scaled_df.head())

from sklearn.decomposition import PCA

# Apply PCA with all 13 components
pca = PCA(n_components=13)
X_pca = pca.fit_transform(X_scaled)

# Display results
print("="*60)
print("✓ PCA APPLIED SUCCESSFULLY!")
print("="*60)
print(f"\n📊 PCA Shape: {X_pca.shape}")
print(f"\n📈 Explained Variance Ratio (per component):")
for i, var in enumerate(pca.explained_variance_ratio_, 1):
    print(f"   PC{i}: {var:.4f} ({var*100:.2f}%)")

print(f"\n📊 Cumulative Explained Variance:")
cumsum = np.cumsum(pca.explained_variance_ratio_)
for i, cum in enumerate(cumsum, 1):
    print(f"   PC1-PC{i}: {cum:.4f} ({cum*100:.2f}%)")

print(f"\n✅ Key Insights:")
print(f"   • First 2 PCs explain: {cumsum[1]*100:.2f}% of variance")
print(f"   • First 3 PCs explain: {cumsum[2]*100:.2f}% of variance")
print(f"   • First 5 PCs explain: {cumsum[4]*100:.2f}% of variance")

# Apply PCA with 5 components
pca_5 = PCA(n_components=5)
X_pca_5 = pca_5.fit_transform(X_scaled)

# Create DataFrame
pca_columns = ['PC1', 'PC2', 'PC3', 'PC4', 'PC5']
X_pca_5_df = pd.DataFrame(X_pca_5, columns=pca_columns)

print("="*60)
print("✓ 5-COMPONENT PCA COMPLETED!")
print("="*60)
print(f"\n📊 Reduced Data Shape: {X_pca_5.shape}")
print(f"   Original: 50,000 × 13")
print(f"   Reduced:  50,000 × 5")
print(f"\n📈 Variance Retained: {pca_5.explained_variance_ratio_.sum()*100:.2f}%")
print(f"\n✅ Variance per Component:")
for i, var in enumerate(pca_5.explained_variance_ratio_, 1):
    print(f"   PC{i}: {var*100:.2f}%")
print(f"\n🔍 First 5 Rows:")
print(X_pca_5_df.head())

from sklearn.manifold import TSNE
import time

print("="*60)
print("⏳ APPLYING t-SNE...")
print("="*60)
print("(This may take 1-2 minutes for 50,000 samples...)")

# Apply t-SNE (2D for visualization)
start_time = time.time()
tsne = TSNE(n_components=2, random_state=42, perplexity=30, n_iter=1000)
X_tsne = tsne.fit_transform(X_pca_5)  # Apply on PCA-reduced data
end_time = time.time()

# Create DataFrame
X_tsne_df = pd.DataFrame(X_tsne, columns=['t-SNE1', 't-SNE2'])

print(f"\n✓ t-SNE COMPLETED!")
print(f"⏱️  Time taken: {end_time - start_time:.2f} seconds")
print(f"\n📊 t-SNE Shape: {X_tsne.shape}")
print(f"\n🔍 First 5 Rows:")
print(X_tsne_df.head())
print(f"\n📈 Statistics:")
print(X_tsne_df.describe())

# Install UMAP
!pip install umap-learn -q

import umap
import time

print("="*60)
print("⏳ APPLYING UMAP...")
print("="*60)
print("(This should be faster than t-SNE...)")

# Apply UMAP (2D for visualization)
start_time = time.time()
umap_model = umap.UMAP(n_components=2, random_state=42, n_neighbors=15, min_dist=0.1)
X_umap = umap_model.fit_transform(X_pca_5)  # Apply on PCA-reduced data
end_time = time.time()

# Create DataFrame
X_umap_df = pd.DataFrame(X_umap, columns=['UMAP1', 'UMAP2'])

print(f"\n✓ UMAP COMPLETED!")
print(f"⏱️  Time taken: {end_time - start_time:.2f} seconds")
print(f"   (t-SNE took: 1277.44 seconds)")
print(f"   Speed improvement: {1277.44/(end_time - start_time):.1f}x faster!")
print(f"\n📊 UMAP Shape: {X_umap.shape}")
print(f"\n🔍 First 5 Rows:")
print(X_umap_df.head())
print(f"\n📈 Statistics:")
print(X_umap_df.describe())

import matplotlib.pyplot as plt

# Create visualization
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# 1. PCA Visualization (first 2 components)
axes[0].scatter(X_pca_5[:, 0], X_pca_5[:, 1], s=1, alpha=0.5, c='blue')
axes[0].set_xlabel('PC1 (48.22% variance)', fontsize=12)
axes[0].set_ylabel('PC2 (16.79% variance)', fontsize=12)
axes[0].set_title('PCA (2D Projection)', fontsize=14, fontweight='bold')
axes[0].grid(True, alpha=0.3)

# 2. t-SNE Visualization
axes[1].scatter(X_tsne[:, 0], X_tsne[:, 1], s=1, alpha=0.5, c='green')
axes[1].set_xlabel('t-SNE Component 1', fontsize=12)
axes[1].set_ylabel('t-SNE Component 2', fontsize=12)
axes[1].set_title('t-SNE (Time: 1277 sec)', fontsize=14, fontweight='bold')
axes[1].grid(True, alpha=0.3)

# 3. UMAP Visualization
axes[2].scatter(X_umap[:, 0], X_umap[:, 1], s=1, alpha=0.5, c='red')
axes[2].set_xlabel('UMAP Component 1', fontsize=12)
axes[2].set_ylabel('UMAP Component 2', fontsize=12)
axes[2].set_title('UMAP (Time: 79 sec)', fontsize=14, fontweight='bold')
axes[2].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('dimensionality_reduction_comparison.png', dpi=150, bbox_inches='tight')
print("✓ Visualization saved as 'dimensionality_reduction_comparison.png'")
plt.show()

print("\n" + "="*60)
print("📊 VISUAL COMPARISON:")
print("="*60)
print("PCA:   Continuous distribution (linear method)")
print("t-SNE: Shows local clustering structure (slow but detailed)")
print("UMAP:  Shows both local and global structure (fast!)")

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# Test K-Means with different k values
k_values = [3, 4, 5, 6, 7]

print("="*60)
print("⏳ APPLYING K-MEANS ON BOTH DATASETS...")
print("="*60)

# Store results
results_pca = {'k': [], 'inertia': [], 'silhouette': []}
results_umap = {'k': [], 'inertia': [], 'silhouette': []}

# Test on PCA data (5D)
print("\n📊 Testing on PCA Data (5 dimensions):")
print("-"*60)
for k in k_values:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(X_pca_5)
    inertia = kmeans.inertia_
    sil_score = silhouette_score(X_pca_5, labels)

    results_pca['k'].append(k)
    results_pca['inertia'].append(inertia)
    results_pca['silhouette'].append(sil_score)

    print(f"k={k}: Inertia={inertia:.2f}, Silhouette={sil_score:.4f}")

# Test on UMAP data (2D)
print("\n📊 Testing on UMAP Data (2 dimensions):")
print("-"*60)
for k in k_values:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(X_umap)
    inertia = kmeans.inertia_
    sil_score = silhouette_score(X_umap, labels)

    results_umap['k'].append(k)
    results_umap['inertia'].append(inertia)
    results_umap['silhouette'].append(sil_score)

    print(f"k={k}: Inertia={inertia:.2f}, Silhouette={sil_score:.4f}")

print("\n✓ K-MEANS TESTING COMPLETED!")

# Apply K-Means with optimal k=3
kmeans_pca = KMeans(n_clusters=3, random_state=42, n_init=10)
labels_kmeans_pca = kmeans_pca.fit_predict(X_pca_5)

kmeans_umap = KMeans(n_clusters=3, random_state=42, n_init=10)
labels_kmeans_umap = kmeans_umap.fit_predict(X_umap)

print("="*60)
print("✓ K-MEANS CLUSTERING COMPLETED (k=3)")
print("="*60)
print(f"\n📊 Cluster Distribution - PCA Data:")
unique, counts = np.unique(labels_kmeans_pca, return_counts=True)
for cluster, count in zip(unique, counts):
    print(f"   Cluster {cluster}: {count} galaxies ({count/len(labels_kmeans_pca)*100:.2f}%)")

print(f"\n📊 Cluster Distribution - UMAP Data:")
unique, counts = np.unique(labels_kmeans_umap, return_counts=True)
for cluster, count in zip(unique, counts):
    print(f"   Cluster {cluster}: {count} galaxies ({count/len(labels_kmeans_umap)*100:.2f}%)")

# Add labels to original dataframe
df['KMeans_PCA'] = labels_kmeans_pca
df['KMeans_UMAP'] = labels_kmeans_umap

print("\n✅ Labels added to dataframe!")

from sklearn.neighbors import NearestNeighbors

print("="*60)
print("⏳ FINDING OPTIMAL EPS FOR DBSCAN...")
print("="*60)

# Function to find optimal eps using k-distance graph
def find_optimal_eps(X, k=5, sample_size=5000):
    # Use sample for speed
    if len(X) > sample_size:
        indices = np.random.choice(len(X), sample_size, replace=False)
        X_sample = X[indices]
    else:
        X_sample = X

    # Compute k-nearest neighbors
    neighbors = NearestNeighbors(n_neighbors=k)
    neighbors.fit(X_sample)
    distances, _ = neighbors.kneighbors(X_sample)

    # Sort distances to kth nearest neighbor
    distances = np.sort(distances[:, k-1])

    # Suggest eps as 90th percentile
    suggested_eps = np.percentile(distances, 90)
    return suggested_eps, distances

# Find eps for PCA data
print("\n📊 Analyzing PCA Data (5D):")
eps_pca, _ = find_optimal_eps(X_pca_5, k=5)
print(f"   Suggested eps: {eps_pca:.3f}")

# Find eps for UMAP data
print("\n📊 Analyzing UMAP Data (2D):")
eps_umap, _ = find_optimal_eps(X_umap, k=5)
print(f"   Suggested eps: {eps_umap:.3f}")

print("\n✓ OPTIMAL EPS VALUES FOUND!")
print

from sklearn.cluster import DBSCAN

print("="*60)
print("⏳ APPLYING DBSCAN...")
print("="*60)

# Apply DBSCAN on PCA data
dbscan_pca = DBSCAN(eps=0.811, min_samples=5)
labels_dbscan_pca = dbscan_pca.fit_predict(X_pca_5)

# Apply DBSCAN on UMAP data
dbscan_umap = DBSCAN(eps=0.306, min_samples=5)
labels_dbscan_umap = dbscan_umap.fit_predict(X_umap)

print("\n✓ DBSCAN COMPLETED!")
print("="*60)

# Analyze PCA results
print(f"\n📊 DBSCAN Results - PCA Data:")
unique_pca, counts_pca = np.unique(labels_dbscan_pca, return_counts=True)
n_clusters_pca = len(unique_pca[unique_pca != -1])
n_noise_pca = counts_pca[unique_pca == -1][0] if -1 in unique_pca else 0
print(f"   Number of clusters: {n_clusters_pca}")
print(f"   Noise points: {n_noise_pca} ({n_noise_pca/len(labels_dbscan_pca)*100:.2f}%)")
for cluster, count in zip(unique_pca, counts_pca):
    if cluster == -1:
        print(f"   Noise: {count} galaxies")
    else:
        print(f"   Cluster {cluster}: {count} galaxies ({count/len(labels_dbscan_pca)*100:.2f}%)")

# Analyze UMAP results
print(f"\n📊 DBSCAN Results - UMAP Data:")
unique_umap, counts_umap = np.unique(labels_dbscan_umap, return_counts=True)
n_clusters_umap = len(unique_umap[unique_umap != -1])
n_noise_umap = counts_umap[unique_umap == -1][0] if -1 in unique_umap else 0
print(f"   Number of clusters: {n_clusters_umap}")
print(f"   Noise points: {n_noise_umap} ({n_noise_umap/len(labels_dbscan_umap)*100:.2f}%)")
for cluster, count in zip(unique_umap, counts_umap):
    if cluster == -1:
        print(f"   Noise: {count} galaxies")
    else:
        print(f"   Cluster {cluster}: {count} galaxies ({count/len(labels_dbscan_umap)*100:.2f}%)")

# Add to dataframe
df['DBSCAN_PCA'] = labels_dbscan_pca
df['DBSCAN_UMAP'] = labels_dbscan_umap

print("\n✅ DBSCAN labels added to dataframe!")

from sklearn.mixture import GaussianMixture

print("="*60)
print("⏳ APPLYING GAUSSIAN MIXTURE MODELS...")
print("="*60)

# Test different numbers of components
n_components = [3, 4, 5, 6, 7]

# Store results
gmm_results_pca = {'n': [], 'bic': [], 'aic': [], 'silhouette': []}
gmm_results_umap = {'n': [], 'bic': [], 'aic': [], 'silhouette': []}

# Test on PCA data
print("\n📊 Testing GMM on PCA Data (5D):")
print("-"*60)
for n in n_components:
    gmm = GaussianMixture(n_components=n, random_state=42, covariance_type='full')
    labels = gmm.fit_predict(X_pca_5)
    bic = gmm.bic(X_pca_5)
    aic = gmm.aic(X_pca_5)
    sil = silhouette_score(X_pca_5, labels)

    gmm_results_pca['n'].append(n)
    gmm_results_pca['bic'].append(bic)
    gmm_results_pca['aic'].append(aic)
    gmm_results_pca['silhouette'].append(sil)

    print(f"n={n}: BIC={bic:.2f}, AIC={aic:.2f}, Silhouette={sil:.4f}")

# Test on UMAP data
print("\n📊 Testing GMM on UMAP Data (2D):")
print("-"*60)
for n in n_components:
    gmm = GaussianMixture(n_components=n, random_state=42, covariance_type='full')
    labels = gmm.fit_predict(X_umap)
    bic = gmm.bic(X_umap)
    aic = gmm.aic(X_umap)
    sil = silhouette_score(X_umap, labels)

    gmm_results_umap['n'].append(n)
    gmm_results_umap['bic'].append(bic)
    gmm_results_umap['aic'].append(aic)
    gmm_results_umap['silhouette'].append(sil)

    print(f"n={n}: BIC={bic:.2f}, AIC={aic:.2f}, Silhouette={sil:.4f}")

print("\n✓ GMM TESTING COMPLETED!")
print("\nNote: Lower BIC/AIC = better, Higher Silhouette = better")

# Apply GMM with optimal n=3
gmm_pca = GaussianMixture(n_components=3, random_state=42, covariance_type='full')
labels_gmm_pca = gmm_pca.fit_predict(X_pca_5)

gmm_umap = GaussianMixture(n_components=3, random_state=42, covariance_type='full')
labels_gmm_umap = gmm_umap.fit_predict(X_umap)

print("="*60)
print("✓ GMM CLUSTERING COMPLETED (n=3)")
print("="*60)

print(f"\n📊 Cluster Distribution - PCA Data:")
unique, counts = np.unique(labels_gmm_pca, return_counts=True)
for cluster, count in zip(unique, counts):
    print(f"   Cluster {cluster}: {count} galaxies ({count/len(labels_gmm_pca)*100:.2f}%)")

print(f"\n📊 Cluster Distribution - UMAP Data:")
unique, counts = np.unique(labels_gmm_umap, return_counts=True)
for cluster, count in zip(unique, counts):
    print(f"   Cluster {cluster}: {count} galaxies ({count/len(labels_gmm_umap)*100:.2f}%)")

# Add to dataframe
df['GMM_PCA'] = labels_gmm_pca
df['GMM_UMAP'] = labels_gmm_umap

print("\n✅ GMM labels added to dataframe!")

from sklearn.cluster import SpectralClustering

print("="*60)
print("⏳ APPLYING SPECTRAL CLUSTERING...")
print("="*60)
print("Note: Using UMAP data only (2D, less memory intensive)")

# Apply Spectral on UMAP data only (2D is safer for memory)
print("\n📊 Applying on UMAP Data (2D)...")
spectral_umap = SpectralClustering(n_clusters=3, random_state=42, affinity='nearest_neighbors', n_neighbors=10)
labels_spectral_umap = spectral_umap.fit_predict(X_umap)

# Calculate silhouette score
sil_spectral_umap = silhouette_score(X_umap, labels_spectral_umap)

print("\n✓ SPECTRAL CLUSTERING COMPLETED!")
print("="*60)

print(f"\n📊 Spectral Results - UMAP Data:")
print(f"   Silhouette Score: {sil_spectral_umap:.4f}")
unique, counts = np.unique(labels_spectral_umap, return_counts=True)
for cluster, count in zip(unique, counts):
    print(f"   Cluster {cluster}: {count} galaxies ({count/len(labels_spectral_umap)*100:.2f}%)")

# Add to dataframe
df['Spectral_UMAP'] = labels_spectral_umap

print("\n✅ Spectral labels added to dataframe!")
print("\nNote: Skipped PCA data (5D) to avoid memory issues")

print("="*60)
print("⏳ APPLYING SPECTRAL CLUSTERING ON PCA DATA...")
print("="*60)
print("⚠️  This may take a few minutes or crash if RAM is insufficient...")

try:
    # Apply Spectral on PCA data (5D)
    spectral_pca = SpectralClustering(n_clusters=3, random_state=42,
                                      affinity='nearest_neighbors',
                                      n_neighbors=10)
    labels_spectral_pca = spectral_pca.fit_predict(X_pca_5)

    # Calculate silhouette score
    sil_spectral_pca = silhouette_score(X_pca_5, labels_spectral_pca)

    print("\n✓ SPECTRAL CLUSTERING ON PCA COMPLETED!")
    print("="*60)

    print(f"\n📊 Spectral Results - PCA Data:")
    print(f"   Silhouette Score: {sil_spectral_pca:.4f}")
    unique, counts = np.unique(labels_spectral_pca, return_counts=True)
    for cluster, count in zip(unique, counts):
        print(f"   Cluster {cluster}: {count} galaxies ({count/len(labels_spectral_pca)*100:.2f}%)")

    # Add to dataframe
    df['Spectral_PCA'] = labels_spectral_pca
    print("\n✅ Spectral PCA labels added to dataframe!")

except Exception as e:
    print(f"\n❌ ERROR: {e}")
    print("Memory insufficient for Spectral on PCA data.")
    print("Proceeding with UMAP results only.")

from sklearn.metrics import davies_bouldin_score, calinski_harabasz_score, adjusted_rand_score
import warnings
warnings.filterwarnings('ignore')

print("="*60)
print("📊 COMPREHENSIVE CLUSTERING EVALUATION")
print("="*60)

# Prepare results storage
results = {
    'Algorithm': [],
    'Dataset': [],
    'Silhouette': [],
    'Davies-Bouldin': [],
    'Calinski-Harabasz': [],
    'N_Clusters': []
}

# Evaluation function
def evaluate_clustering(X, labels, algo_name, dataset_name):
    # Filter out noise points for DBSCAN (label -1)
    mask = labels != -1
    X_filtered = X[mask]
    labels_filtered = labels[mask]

    n_clusters = len(np.unique(labels_filtered))

    if n_clusters > 1 and len(labels_filtered) > 0:
        sil = silhouette_score(X_filtered, labels_filtered)
        db = davies_bouldin_score(X_filtered, labels_filtered)
        ch = calinski_harabasz_score(X_filtered, labels_filtered)
    else:
        sil, db, ch = None, None, None

    results['Algorithm'].append(algo_name)
    results['Dataset'].append(dataset_name)
    results['Silhouette'].append(sil)
    results['Davies-Bouldin'].append(db)
    results['Calinski-Harabasz'].append(ch)
    results['N_Clusters'].append(n_clusters)

# Evaluate all algorithms on PCA data
print("\n🔍 Evaluating PCA Data (5D)...")
evaluate_clustering(X_pca_5, labels_kmeans_pca, 'K-Means', 'PCA')
evaluate_clustering(X_pca_5, labels_dbscan_pca, 'DBSCAN', 'PCA')
evaluate_clustering(X_pca_5, labels_gmm_pca, 'GMM', 'PCA')
evaluate_clustering(X_pca_5, labels_spectral_pca, 'Spectral', 'PCA')

# Evaluate all algorithms on UMAP data
print("🔍 Evaluating UMAP Data (2D)...")
evaluate_clustering(X_umap, labels_kmeans_umap, 'K-Means', 'UMAP')
evaluate_clustering(X_umap, labels_dbscan_umap, 'DBSCAN', 'UMAP')
evaluate_clustering(X_umap, labels_gmm_umap, 'GMM', 'UMAP')
evaluate_clustering(X_umap, labels_spectral_umap, 'Spectral', 'UMAP')

# Create results dataframe
results_df = pd.DataFrame(results)

print("\n✓ EVALUATION COMPLETED!")
print("\n" + "="*60)
print("📋 CLUSTERING PERFORMANCE COMPARISON")
print("="*60)
print(results_df.to_string(index=False))

print("\n" + "="*60)
print("📊 INTERPRETATION:")
print("="*60)
print("✅ Silhouette Score: Higher is better (range: -1 to 1)")
print("✅ Davies-Bouldin Index: Lower is better")
print("✅ Calinski-Harabasz Score: Higher is better")

# Save evaluation results
results_df.to_csv('clustering_evaluation_comparison.csv', index=False)
print("✅ Evaluation results saved as 'clustering_evaluation_comparison.csv'")

# Identify best algorithm
best_idx = results_df['Silhouette'].idxmax()
best_algo = results_df.loc[best_idx]
print(f"\n🏆 BEST PERFORMING ALGORITHM:")
print(f"   {best_algo['Algorithm']} on {best_algo['Dataset']} data")
print(f"   Silhouette: {best_algo['Silhouette']:.4f}")
print(f"   Davies-Bouldin: {best_algo['Davies-Bouldin']:.4f}")

import matplotlib.pyplot as plt

# Create comprehensive visualization
fig, axes = plt.subplots(2, 4, figsize=(20, 10))

# Row 1: PCA Data Results
algorithms_pca = [
    ('K-Means', labels_kmeans_pca),
    ('DBSCAN', labels_dbscan_pca),
    ('GMM', labels_gmm_pca),
    ('Spectral', labels_spectral_pca)
]

for idx, (name, labels) in enumerate(algorithms_pca):
    scatter = axes[0, idx].scatter(X_pca_5[:, 0], X_pca_5[:, 1],
                                   c=labels, s=1, alpha=0.5, cmap='viridis')
    axes[0, idx].set_xlabel('PC1', fontsize=10)
    axes[0, idx].set_ylabel('PC2', fontsize=10)
    axes[0, idx].set_title(f'{name} on PCA\n({len(np.unique(labels))} clusters)',
                          fontsize=12, fontweight='bold')
    axes[0, idx].grid(True, alpha=0.3)

# Row 2: UMAP Data Results
algorithms_umap = [
    ('K-Means', labels_kmeans_umap),
    ('DBSCAN', labels_dbscan_umap),
    ('GMM', labels_gmm_umap),
    ('Spectral', labels_spectral_umap)
]

for idx, (name, labels) in enumerate(algorithms_umap):
    scatter = axes[1, idx].scatter(X_umap[:, 0], X_umap[:, 1],
                                   c=labels, s=1, alpha=0.5, cmap='viridis')
    axes[1, idx].set_xlabel('UMAP1', fontsize=10)
    axes[1, idx].set_ylabel('UMAP2', fontsize=10)
    axes[1, idx].set_title(f'{name} on UMAP\n({len(np.unique(labels))} clusters)',
                          fontsize=12, fontweight='bold')
    axes[1, idx].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('all_clustering_results.png', dpi=150, bbox_inches='tight')
print("✅ Visualization saved as 'all_clustering_results.png'")
plt.show()

print("\n" + "="*60)
print("📊 VISUAL OBSERVATIONS:")
print("="*60)
print("• Top row shows PCA results (5D projected to 2D)")
print("• Bottom row shows UMAP results (native 2D)")
print("• K-Means and GMM show clear 3-cluster separation")
print("• DBSCAN struggles with continuous density")
print("• UMAP embeddings reveal better cluster structure")

# Use K-Means on UMAP labels (best performing)
cluster_labels = df['KMeans_UMAP']

print("="*60)
print("🔭 SCIENTIFIC INTERPRETATION OF GALAXY CLUSTERS")
print("="*60)

# Analyze each cluster
for cluster in range(3):
    cluster_data = df[cluster_labels == cluster]
    n_galaxies = len(cluster_data)

    print(f"\n{'='*60}")
    print(f"CLUSTER {cluster} ({n_galaxies} galaxies, {n_galaxies/len(df)*100:.1f}%)")
    print(f"{'='*60}")

    # Galaxy Colors (key for galaxy type)
    print(f"\n📊 Galaxy Colors (magnitudes):")
    print(f"   u-g: {cluster_data['u-g'].mean():.3f} ± {cluster_data['u-g'].std():.3f}")
    print(f"   g-r: {cluster_data['g-r'].mean():.3f} ± {cluster_data['g-r'].std():.3f}")
    print(f"   r-i: {cluster_data['r-i'].mean():.3f} ± {cluster_data['r-i'].std():.3f}")
    print(f"   i-z: {cluster_data['i-z'].mean():.3f} ± {cluster_data['i-z'].std():.3f}")

    # Redshift (distance/age)
    print(f"\n🌌 Redshift Distribution:")
    print(f"   Mean: {cluster_data['redshift'].mean():.4f}")
    print(f"   Median: {cluster_data['redshift'].median():.4f}")
    print(f"   Range: {cluster_data['redshift'].min():.4f} - {cluster_data['redshift'].max():.4f}")

    # Morphology
    print(f"\n🔍 Morphology (Petrosian Radius in r-band):")
    print(f"   Mean petroRad_r: {cluster_data['petroRad_r'].mean():.2f} arcsec")
    print(f"   Mean petroR50_r: {cluster_data['petroR50_r'].mean():.2f} arcsec (half-light)")

    # Magnitudes
    print(f"\n💡 Absolute Brightness:")
    print(f"   r-band magnitude: {cluster_data['r'].mean():.2f} ± {cluster_data['r'].std():.2f}")

print("\n" + "="*60)
print("🔬 ASTROPHYSICAL INTERPRETATION")
print("="*60)

# Create cluster properties summary table
cluster_summary = []

for cluster in range(3):
    cluster_data = df[df['KMeans_UMAP'] == cluster]

    summary = {
        'Cluster': cluster,
        'N_Galaxies': len(cluster_data),
        'Percentage': f"{len(cluster_data)/len(df)*100:.1f}%",
        'u-g_mean': f"{cluster_data['u-g'].mean():.3f}",
        'g-r_mean': f"{cluster_data['g-r'].mean():.3f}",
        'Redshift_mean': f"{cluster_data['redshift'].mean():.4f}",
        'r_mag_mean': f"{cluster_data['r'].mean():.2f}",
        'petroRad_r_mean': f"{cluster_data['petroRad_r'].mean():.2f}",
        'Galaxy_Type': ['Blue Star-Forming', 'Red Quiescent', 'Intermediate'][cluster] if cluster in [0,1,2] else 'Unknown'
    }
    cluster_summary.append(summary)

# Create DataFrame
summary_df = pd.DataFrame(cluster_summary)

# Reorder based on astrophysical interpretation
summary_df = summary_df.iloc[[2, 0, 1]]  # Blue, Intermediate, Red
summary_df['Galaxy_Type'] = ['Blue Star-Forming Spirals', 'Intermediate/Green Valley', 'Red Quiescent Ellipticals']

print("="*60)
print("📋 GALAXY CLUSTER SUMMARY TABLE")
print("="*60)
print(summary_df.to_string(index=False))

# Save summary
summary_df.to_csv('galaxy_cluster_summary.csv', index=False)
print("\n✅ Summary saved as 'galaxy_cluster_summary.csv'")

# Save the final clustered dataset
df.to_csv('galaxy_dataset_clustered.csv', index=False)
print("✅ Full dataset with cluster labels saved as 'galaxy_dataset_clustered.csv'")

print("\n" + "="*60)
print("📦 FINAL DELIVERABLES CHECKLIST")
print("="*60)
print("✅ 1. Jupyter Notebook (current file)")
print("✅ 2. Clustered Dataset: galaxy_dataset_clustered.csv")
print("✅ 3. Evaluation Results: clustering_evaluation_comparison.csv")
print("✅ 4. Cluster Summary: galaxy_cluster_summary.csv")
print("✅ 5. Visualizations:")
print("      - dimensionality_reduction_comparison.png")
print("      - all_clustering_results.png")

# Create requirements.txt file
requirements = """numpy==1.24.3
pandas==2.0.3
matplotlib==3.7.2
scikit-learn==1.3.0
umap-learn==0.5.3
"""

with open('requirements.txt', 'w') as f:
    f.write(requirements)

print("="*60)
print("✅ requirements.txt CREATED!")
print("="*60)
print(requirements)